### ISSUE TITLE
Errno::ENOENT: No such file or directory for snakeyaml on jruby-head

### ISSUE THREAD

**Issue by sl0thentr0py** [ruby/psych#700]
Our CI on `sentry-ruby` is failing because of this snakeyaml error:

```
Errno::ENOENT: No such file or directory - /home/runner/.m2/repository/org/snakeyaml/snakeyaml-engine/2.7/snakeyaml-engine-2.7.jar -- module org.snakeyaml.engine.v2
```

See our action logs here:
https://github.com/getsentry/sentry-ruby/actions/runs/12278203115/job/34259414144?pr=2490#step:4:141

**Comment by flavorjones** [comment]
@headius I'm not sure if you're aware of this issue, but right now this is breaking JRuby test suites for folks who applied the "pin jar-dependencies" fix from https://github.com/jruby/jruby/pull/8502 and https://github.com/jruby/jruby/issues/7262. See for example:

- https://github.com/sparklemotion/mechanize/actions/runs/12427720237/job/34698022038
- https://github.com/sparklemotion/nokogiri/actions/runs/12427722368/job/34698028585

in addition to the sentry-ruby log above.

**Comment by headius** [comment]
I'm thinking we might be able to safely yank the new jar-dependencies and re-release once JRuby 9.4.10.0 is out with the fix.

**Comment by sl0thentr0py** [comment]
we are still seeing this after removing all the pins
https://github.com/getsentry/sentry-ruby/actions/runs/13114633511/job/36586215743?pr=2536#step:4:145

the versions for this run are
```
Installing psych 5.2.3 (java)
Installing jar-dependencies 0.5.3
```

**Comment by headius** [comment]
Working on this today.

**Comment by headius** [comment]
I have released jar-dependencies 0.5.4, and I believe if you remove your pinned versions and install that gem, it should work properly for you. You can see some discussion and other workarounds in jruby/jruby#8606.

Please let me know if you can't get it to work, because I'm actively trying to chase down these last few bugs!

**Comment by solnic** [comment]
@headius thanks for working on this, unfortunately it's still not bundling on our CI https://github.com/getsentry/sentry-ruby/actions/runs/13198501845/job/36845061899?pr=2550#step:4:80

**Comment by headius** [comment]
@solnic I provided several workarounds above, did you try them? All I see here is jar-dependencies being installed about halfway through bundling in parallel, which I pointed out above may not be early enough. Try moving it up in your dependencies, installing it **before** bundling, or using jruby-head.

**Comment by headius** [comment]
Also just released jar-dependencies 0.5.5 which cleans up the fix a bit.

**Comment by stackmystack** [comment]
This issue is fixed for me with jruby 9.4.10, but comes back on with jruby 9.4.11.

https://github.com/Faveod/arel-extensions/actions/runs/13245454778/job/36972182865

**Comment by headius** [comment]
@stackmystack We will release 9.4.12.0 this week with a fixed jar-dependencies. See jruby/jruby#8606.

**Comment by hsbt** [comment]
Fixed by the jar-dependencies update in JRuby 9.4.12.0 (jruby/jruby#8606). Closing.
